"""
overlay.py
----------
Generates the patient-friendly, quadrant-annotated overlay (translucent
colored regions + Q1-Q4 boxes + finding labels) in the style of the
reference figure, using the REAL threshold vector produced by
standard_sma() / enhanced_sma() -- not a hardcoded t1/t2 like the old
placeholder code.

HOW THE LABELS WORK (read this before using in your defense):
The 4 darkest intensity bands produced by the optimal threshold vector
are mapped, by darkness rank, to a fixed 4-category legend:

    band 0 (darkest)  -> "Impacted"
    band 1            -> "Caries"
    band 2            -> "Periapical Lesion"
    band 3 (lightest of the 4) -> "Deep Caries"

This is a DARKNESS-RANK heuristic, not a trained classifier -- the
algorithm has no way to actually tell an impacted tooth from a
periapical lesion, it only knows "this region falls in the Nth-darkest
intensity band." Two regions with identical shapes will get different
labels purely because of which band they landed in. For your Chapter 4
/ Chapter 5, you should be explicit that this labeling is illustrative
(matches the visual convention you were asked to follow) and not a
validated diagnostic classification -- an actual per-lesion classifier
would need a labeled dataset and a trained model on top of the
segmentation this system already does correctly.

Because real patients may see this output, the API response and the
UI both carry a non-clinical disclaimer -- keep that disclaimer visible
in whatever screen renders this image.
"""

import cv2
import numpy as np

DISCLAIMER = (
    "Research prototype for academic demonstration only. This output is "
    "NOT a clinical diagnosis. Findings are generated by an intensity "
    "threshold heuristic, not a validated diagnostic model. Please "
    "consult a licensed dentist for any actual diagnosis or treatment."
)

# BGR colors (OpenCV order) matching the quadrant color scheme in the
# reference figure: Q1=green, Q2=red, Q3=blue, Q4=yellow
QUADRANT_COLORS = {
    "Q1": (0, 170, 0),
    "Q2": (0, 0, 220),
    "Q3": (200, 130, 0),
    "Q4": (0, 210, 210),
}

# darkness-rank band index -> label (see module docstring for caveats)
BAND_LABELS = {
    0: "Impacted",
    1: "Caries",
    2: "Periapical Lesion",
    3: "Deep Caries",
}


def _detect_dental_arch_band(gray_image, x0, x1):
    """
    Auto-detects the vertical (y) band that actually contains the teeth,
    instead of a fixed fraction of image height. Teeth/roots produce much
    higher local contrast (edges) than sinus cavities or soft tissue, so
    we use row-wise edge energy to find the band, with safety fallbacks.
    """
    h = gray_image.shape[0]
    strip = gray_image[:, x0:x1].astype(np.float32)
    lap = cv2.Laplacian(strip, cv2.CV_32F, ksize=3)
    row_energy = np.mean(np.abs(lap), axis=1)

    # smooth the row-energy profile
    k = max(5, h // 60)
    kernel = np.ones(k, dtype=np.float32) / k
    row_energy = np.convolve(row_energy, kernel, mode="same")

    threshold = np.percentile(row_energy, 55)
    above = row_energy > threshold

    # find the longest contiguous run of rows above threshold
    best_start, best_len, cur_start, cur_len = 0, 0, 0, 0
    for i, v in enumerate(above):
        if v:
            if cur_len == 0:
                cur_start = i
            cur_len += 1
            if cur_len > best_len:
                best_start, best_len = cur_start, cur_len
        else:
            cur_len = 0

    if best_len < h * 0.12:
        # detection failed / too small a band -- fall back to a safe default
        return int(h * 0.30), int(h * 0.85)

    y0, y1 = best_start, best_start + best_len
    # small margin, then clamp to sane bounds
    margin = int(best_len * 0.08)
    y0 = max(int(h * 0.08), y0 - margin)
    y1 = min(int(h * 0.95), y1 + margin)
    return y0, y1


def _quadrant_for(cx, cy, x_mid, y_mid):
    if cx < x_mid and cy < y_mid:
        return "Q1"
    if cx >= x_mid and cy < y_mid:
        return "Q2"
    if cx >= x_mid and cy >= y_mid:
        return "Q3"
    return "Q4"


def _iou(a, b):
    ax0, ay0, aw, ah = a
    bx0, by0, bw, bh = b
    ax1, ay1 = ax0 + aw, ay0 + ah
    bx1, by1 = bx0 + bw, by0 + bh
    ix0, iy0 = max(ax0, bx0), max(ay0, by0)
    ix1, iy1 = min(ax1, bx1), min(ay1, by1)
    iw, ih = max(0, ix1 - ix0), max(0, iy1 - iy0)
    inter = iw * ih
    if inter == 0:
        return 0.0
    union = aw * ah + bw * bh - inter
    return inter / union


def _non_max_suppress(regions, iou_thresh=0.25, max_per_quadrant=6):
    """
    Greedy NMS: sort by area (bigger = more likely a real finding, not
    noise), drop anything that heavily overlaps something already kept,
    and cap how many findings we show per quadrant so the output stays
    readable instead of a wall of stacked labels.
    """
    regions = sorted(regions, key=lambda r: r["area_px"], reverse=True)
    kept = []
    counts = {"Q1": 0, "Q2": 0, "Q3": 0, "Q4": 0}
    for r in regions:
        if counts[r["quadrant"]] >= max_per_quadrant:
            continue
        if any(_iou(r["bbox"], k["bbox"]) > iou_thresh for k in kept):
            continue
        kept.append(r)
        counts[r["quadrant"]] += 1
    return kept


def generate_annotated_overlay(
    gray_image: np.ndarray,
    thresholds,
    roi_x=(0.03, 0.97),
    min_area_frac=0.00025,   # relative to ROI area -- scales with image size
    max_area_frac=0.02,
    min_aspect=0.3,
    max_aspect=3.0,
    iou_thresh=0.25,
    max_per_quadrant=6,
):
    """
    Returns (overlay_image_bgr, detected_regions, quadrant_summary).
    """
    h, w = gray_image.shape
    output = cv2.cvtColor(gray_image, cv2.COLOR_GRAY2BGR)
    overlay = output.copy()

    x0, x1 = int(w * roi_x[0]), int(w * roi_x[1])
    y0, y1 = _detect_dental_arch_band(gray_image, x0, x1)
    x_mid, y_mid = w / 2.0, (y0 + y1) / 2.0

    roi_mask = np.zeros((h, w), dtype=np.uint8)
    roi_mask[y0:y1, x0:x1] = 255
    roi_area = (y1 - y0) * (x1 - x0)
    min_area = max(80, roi_area * min_area_frac)
    max_area = roi_area * max_area_frac

    close_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))

    bounds = [0] + sorted(int(round(t)) for t in thresholds) + [256]
    candidates = []

    for band_idx in range(len(bounds) - 1):
        label = BAND_LABELS.get(band_idx)
        if label is None:
            continue  # lighter bands (healthy bone/enamel) are not flagged

        lo, hi = bounds[band_idx], bounds[band_idx + 1]
        if hi <= lo:
            continue

        intensity_mask = cv2.inRange(gray_image, lo, max(hi - 1, lo))
        mask = cv2.bitwise_and(intensity_mask, roi_mask)
        # merge nearby speckle into coherent blobs, drop single-pixel noise
        mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, close_kernel)
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, close_kernel)

        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if not (min_area < area < max_area):
                continue
            x, y, bw, bh = cv2.boundingRect(cnt)
            aspect = bw / float(bh) if bh > 0 else 0
            if not (min_aspect < aspect < max_aspect):
                continue

            cx, cy = x + bw / 2.0, y + bh / 2.0
            quadrant = _quadrant_for(cx, cy, x_mid, y_mid)
            mean_intensity = float(gray_image[y:y + bh, x:x + bw].mean())
            candidates.append({
                "quadrant": quadrant,
                "label": label,
                "bbox": [int(x), int(y), int(bw), int(bh)],
                "area_px": int(area),
                "mean_intensity": round(mean_intensity, 2),
            })

    detected = _non_max_suppress(candidates, iou_thresh=iou_thresh, max_per_quadrant=max_per_quadrant)

    for region in detected:
        x, y, bw, bh = region["bbox"]
        color = QUADRANT_COLORS[region["quadrant"]]
        overlay_patch = overlay[y:y + bh, x:x + bw]
        color_patch = np.full_like(overlay_patch, color, dtype=np.uint8)
        overlay[y:y + bh, x:x + bw] = color_patch
        cv2.rectangle(output, (x, y), (x + bw, y + bh), color, 2)

    blended = cv2.addWeighted(overlay, 0.30, output, 0.70, 0)

    for region in detected:
        x, y, bw, bh = region["bbox"]
        color = QUADRANT_COLORS[region["quadrant"]]
        text = f'Q={region["quadrant"][1]} D={region["label"]}'
        ty = max(y - 8, 15)
        cv2.putText(blended, text, (x, ty), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 0, 0), 3, cv2.LINE_AA)
        cv2.putText(blended, text, (x, ty), cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 1, cv2.LINE_AA)

    # quadrant divider guide lines (subtle, like reference figure (a))
    cv2.line(blended, (int(x_mid), y0), (int(x_mid), y1), (150, 150, 150), 1)
    cv2.line(blended, (x0, int(y_mid)), (x1, int(y_mid)), (150, 150, 150), 1)

    quadrant_summary = {"Q1": 0, "Q2": 0, "Q3": 0, "Q4": 0}
    for region in detected:
        quadrant_summary[region["quadrant"]] += 1

    return blended, detected, quadrant_summary